name: daty
description: An app to remember all birthdays.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: any
  awesome_notifications: any
  flutter_launcher_icons: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_ios: "images/app_icon_ios.png"
  image_path_android: "images/app_icon_android.png"
  adaptive_icon_background: "images/app_icon_android_background.png"
  adaptive_icon_foreground: "images/app_icon_android_foreground.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/app_icon_android.png"
  windows:
    generate: true
    image_path: "images/app_icon_ios.png"
    icon_size: 48

flutter_native_splash:
  image: images/app_splash.png
  background_image: images/app_background.png

flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
